### PR TITLE
error

### PR DESCRIPTION
**Pull request by jburel**
Fix 404 error

Check that there is no 404 error when "exploring" the gallery on cowfish

### CODE REVIEW

**Comment by waxenegger** [comment]
To be honest, I have not found "explore" on https://cowfish.openmicroscopy.org/webtrial/gallery.

I did call the view that uses the template that contains the script link and the js is question is loaded, both locally and on cowfish, but I have no idea how to navigate there. Because of that, I suspect, I the viewer bit that is embedded complains about the missing OME context when trying to load.

**Comment by jburel** [comment]
sorry for the confusion. I meant "using gallery"

**Comment by waxenegger** [comment]
ok, thank you for the clarification. I'm going to follow all links and check for 404s then. 
 
Is there a way to get to /show_image/image_id by means of navigation or is that kind of a dead/orphaned path?

**Comment by will-moore** [comment]
@waxenegger I think that ```show_image``` was probably used before being replaced by ```webgateway_full_viewer``` so I don't think you can navigate to it now.

**Comment by waxenegger** [comment]
Ah I see, thanks will.

In that case I haven't encountered any 404s or other errors and things seem to behave just fine.

**Pull request merged**
