### PR TITLE
python 3 fixes

### PR DESCRIPTION
**Pull request by will-moore**
Fixes to work with python 3 on Django 1.11

### CODE REVIEW

**Comment by joshmoore** [comment]
```diff
- 
+ Green!
```

**Comment by sbesson** [comment]
Thanks @will-moore, our last tag was `3.2.0a8`. Should we get a final `3.2.0` release of the current production gallery and tag this as `3.3.dev1` with Python3 support alongside the other apps?

**Comment by will-moore** [comment]
@sbesson sounds good.

**Comment by manics** [comment]
Decided today: straight to `3.3.dev1`

**Comment by sbesson** [comment]
As mentioned in https://github.com/ome/omero-gallery/pull/47#issuecomment-555930319, switching to the `3.3.dev1`. If required, we can branch off from the latest tag `3.2.0a8` and get a production tag at a later stage.

**Pull request merged**
