### PR TITLE
Show spinner handle failed calls and show table for MAPR results

### PR DESCRIPTION
**Pull request by will-moore**
Following Monday's testing and ongoing discussions, this aims to improve the user experience when MAPR calls take a long time or time-out and updates the MAPR results layout to show a table

 - Show a spinner when filtering by MAPR
 - Handle timeouts with a 'server busy' message
 - Also improve the MAPR results layout (clearer that images are separate links to viewer)
 - Don't zoom Study images on hover.
 - Show MAPR filter results in a table for each variant of gene name e.g. TOP2, Top2.
    - Include link to the images themselves (and a link to the study)
 - Sort by date "latest" based on "Release Date" key-value pair on each study.
 - Each study now has "first author et al" linking to the publication.

### CODE REVIEW

**Comment by will-moore** [comment]
@sbesson Sorry, just pushed this (missed the closing of the other branch PR yesterday).

**Comment by manics** [comment]
Looks mostly OK.
One error in the Firefox console, looks like something is trying to load a font as a stylesheet?
Screen Shot 2019-06-04 at 09 54 05

Issues unrelated to this PR (can be handled separately to keep this PR clean)
- The tooltip starts with `Experiment description`, I don't think this is needed
Screen Shot 2019-06-04 at 10 08 04
- IDR gallery doesn't work in Internet Explorer 11. If this is going to be the main IDR home page we'll need to agree on what browsers must be supported.

**Comment by will-moore** [comment]
Last commit fixes bug reported by @jrswedlow where thumbnails don't load on e.g. ```/gallery/search/?query=mapr_phenotype:de-enriched%20for%20slightly%20elongated```

**Comment by will-moore** [comment]
- Fixed the "Experiment Description" in tooltip.
 - Fixed font/stylesheet error above.
 - Fixed bug reported by Jason (see https://github.com/ome/omero-gallery/pull/30#issuecomment-498627763)
 - Fixed tiny icons on footer of the /search page
 - Improved usability of auto-complete with "Studies Attributes":
    - After choosing an auto-complete option and text updates with this text... Next time user clicks on auto-complete input, we show ALL options (previously we only showed options that match current text (1 option)).
    - Also clicking on input selects all text to make it easier to enter new text.
 - Added tag-line (home page, and cell/tissue pages), and orange buttons and smaller images on home page: 
Screen Shot 2019-06-04 at 23 02 41

Compiling JavaScript to support IE will go in another PR.

**Pull request merged**
