### PR TITLE
rename

### PR DESCRIPTION
**Pull request by jburel**
update following repo renaming
https://testpypi.python.org/pypi?:action=display&name=omero-gallery&version=2.0.5

cc @sbesson @aleksandra-tarkowska

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
I think you still need to fix readme links like  `http://ome.github.io/gallery/images/webgateway_viewer.png` to point to the new location

**Comment by jburel** [comment]
good catch

**Comment by aleksandra-tarkowska** [comment]
@jburel I know that is not the part of this PR but could you replace `` tag with  `.. image::`

**Comment by aleksandra-tarkowska** [comment]
could you try https://github.com/jburel/omero-gallery/pull/1. it looks ok in https://github.com/aleksandra-tarkowska/omero-gallery/tree/rename

**Comment by jburel** [comment]
@aleksandra-tarkowska it looks good on testpypi https://testpypi.python.org/pypi?:action=display&name=omero-gallery&version=2.0.8

**Pull request merged**
