### PR TITLE
Show different subheading for /cell and /tissue

### PR DESCRIPTION
**Pull request by will-moore**
- Tweak the text on /cell and /tissue pages.
 - Remove empty studies from /gallery/ e.g.  ```/search/?query=Name:idr0028``` shouldn't show the empty idr0028 study.

### CODE REVIEW

**Comment by will-moore** [comment]
https://github.com/ome/omero-gallery/pull/37/commits/fb5f565ee79e26d263aeda6444576eb8f0fb81d0 breaks thumbnails because the /gallery/gallery-api/ URL isn't 'public' now that /gallery/ is deployed at root (https://github.com/openmicroscopy/openmicroscopy/pull/6046).
Other pages at e.g. /gallery/cell/ at /cell/ don't need a login.

**Comment by manics** [comment]
See https://github.com/IDR/deployment/pull/182

It'd be great if someone can explain the logic of why only `/gallery-api` needs to be added to the public filter, but `/gallery` doesn't.

**Comment by will-moore** [comment]
```gallery/gallery-api/thumbnails/``` is the only gallery URL that needs to allow auto-login for public user. The other pages don't need a login because they load all their data via JSON urls that are already public e.g. ```/api/``` or ```/mapr/```.

**Comment by manics** [comment]
Merging as I'm running into conflicts

**Pull request merged**
